spring.application.name=webboard

server.port=8080

# 로그 색상
spring.output.ansi.enabled=always

# 로그 설정
logging.level.root=info

## Oracle DB Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=studygroup
spring.datasource.password=java12345

# ## JPA DB settings
# Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# create : 서버가 실행될 때마다 새로운 테이블 생성, update : 최초 없으면 생성, 이전 DB를 그대로 보관
spring.jpa.hibernate.ddl-auto=none

# 로그 쿼리 출력
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
